service: demo-service
description: Sample knative service
provider:
  name: triggermesh
  registry: knative.registry.svc.cluster.local
functions:
  python-function:
    source: handler.py
    runtime: https://raw.githubusercontent.com/triggermesh/runtime-build-tasks/master/aws-lambda/python37-runtime.yaml
    buildargs:
    - HANDLER=handler.endpoint
    environment:
      EVENT: API_GATEWAY
      foo: bar
